### ISSUE TITLE
Add support for GetPrefix operation in dskit/kv

### ISSUE THREAD

**Issue by ortuman** [grafana/dskit#106]
Both `consul` and `etcd` support the possibility to atomically fetch a given set objects starting with a key prefix. Would be desirable to support this in dskit/kv as it might be useful for certain use cases.

**Comment by pracucci** [comment]
Which use case need it?

**Comment by ortuman** [comment]
Let's imagine we have a huge value object that has to be stored into KV and shared across different instances. To avoid watching a single key and bringing the whole object into memory whenever it gets updated, we could split each of the instance fields into different keys (eg. `ring://<instance_id>/state`, `ring://<instance_id>/tokens`, etc.) and watch the common prefix to obtain delta changes. However, when a new instance joins the cluster we'd like to atomically bring the current object view into memory without having to iterate each of its keys. That's where `GetPrefix`operation would be necessary. 

Note this approach, and for this specific use case, would not only help to reduce traffic from KV store to the clients but would also address the maximum [value size limitation](https://www.consul.io/docs/agent/options#kv_max_value_size).

**Comment by pracucci** [comment]
Yes, I see your point, however I think the future of ring is memberlist (which already solves this and other scalability issues).

**Comment by ortuman** [comment]
In that case this isn't a priority at all. 

Thanks for the feedback @pracucci! 👍
