### ISSUE TITLE
Empty ring right after startup when using memberlist

### ISSUE THREAD

**Issue by pracucci** [grafana/dskit#184]
In Mimir, we're occasionally seeing "empty ring" ring right after a process startup (e.g. querier). It's an issue that has started after the migration to memberlist.

## Possible root cause

I think the issue is caused by the ring client implementation not guaranteeing to wait to get the initial ring state before switching to `Running` state. In the following I share some thoughts about the code.

The ring client service is expected to switch to `Running` state only after it initialized its internal state with the ring data structure. This is why it calls `r.KVClient.Get()` in the `Ring.starting()`:
https://github.com/grafana/dskit/blob/e441b77be7780e03f2c37659839bfe90dfde7dd3/ring/ring.go#L252-L256

When using Consul or etcd as backend, the `r.KVClient.Get()` guarantees to return the state of the ring, but I think this guarantee has been lost in the memberlist implementation and it could return a zero data structure.

The memberlist client `Get()` is implemented here:
https://github.com/grafana/dskit/blob/e441b77be7780e03f2c37659839bfe90dfde7dd3/kv/memberlist/memberlist_client.go#L63-L70

It waits until the backend KV client is running. But does waiting for it to be running guarantee the ring data structure to be populated before that? I don't think so.

The memberlist `KV.starting()` just initialise memberlist but doesn't join the cluster:
https://github.com/grafana/dskit/blob/e441b77be7780e03f2c37659839bfe90dfde7dd3/kv/memberlist/memberlist_client.go#L426-L453

The memberlist cluster is joined only in the `KV.running()`, but that's too late, because at that point our code assume the ring data structure to be already populated:
https://github.com/grafana/dskit/blob/e441b77be7780e03f2c37659839bfe90dfde7dd3/kv/memberlist/memberlist_client.go#L457-L472

**Comment by pstibrany** [comment]
Joining the memberlist cluster or even getting full state from another node are no guarantees that KV store is complete or up to date. Shall we just introduce "wait" period into KV store operations and return error or block before this wait period has elapsed?

Note that lifecyclers already have option to "observe" the ring for similar reason (to avoid generating conflicting tokens).

**Comment by bboreham** [comment]
Let's add some cases:
* 10 ingesters are running; this process is a querier that expects to learn about them via memberlist (I think this is the case you had in mind).
* This process is, and will be, the only one in the ring.
* 100 processes just started up; we have managed to join a memberlist with 2 of them, and 97 more will join shortly.

**Comment by pracucci** [comment]
> Joining the memberlist cluster or even getting full state from another node are no guarantees that KV store is complete or up to date. 

Is this true given the initial "state pull"? Couldn't we wait for the "state pull" (from a random node) to be completed^

**Comment by colega** [comment]
Just to confirm the theory of going into running state without having ring information: I can see the log `ring doesn't exist in KV store yet` from `starting()` right before the querier starts and responds `empty ring` to all queries.

https://github.com/grafana/dskit/blob/e441b77be7780e03f2c37659839bfe90dfde7dd3/ring/ring.go#L255-L265

**Comment by pstibrany** [comment]
> Is this true given the initial "state pull"? Couldn't we wait for the "state pull" (from a random node) to be completed?

What if the other random node didn't have full state yet? However looking at `Join` implementation, it contacts all nodes and does state sync with all of them (one by one).

What if we moved initial join of cluster to `starting` method. Right now it is in `running` state, but at that point `Client` can already return empty ring. By moving "joining" into `starting`, `Client` would wait until node has fully joined the memberlist cluster.

There is a [comment in `running`](https://github.com/grafana/dskit/blob/99f3d0043c23665adadad60d53bd8be5a3a3e354/kv/memberlist/memberlist_client.go#L466-L481) saying that we don't really want that, because `Client` can work with empty KV store too. That is true, but such client is not very helpful as we can see in this issue.

To avoid breaking other clients, perhaps we could try to introduce "join-in-starting" flag to try it out in our setup.

**Comment by pstibrany** [comment]
PR #195 changes memberlist `KV` to join cluster in `Starting` state. This would fix the problem, but would also slow down the start of the service. Perhaps we can try mixed approach: join some subset of nodes in `Starting` state and continue with remaining joins in `Running` state. This could minimize risk of running with empty KV store, while making sure that we don’t create split memberlist clusters.

**Comment by pracucci** [comment]
> Perhaps we can try mixed approach

The mixed approach looks more interesting. I don't want joining to be an operation which linearly increase with the number of nodes.

**Comment by pstibrany** [comment]
> The mixed approach looks more interesting. I don't want joining to be an operation which linearly increase with the number of nodes.

PR https://github.com/grafana/dskit/pull/195 now implements "fast-join" in `Starting` state and "regular" join (all nodes) in `Running` state.
