### ISSUE TITLE
Flaky `TestRing_ShuffleShardWithLookback_CorrectnessWithFuzzy`

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/dskit#221]
The test failed in [this run](https://drone.grafana.net/grafana/dskit/1420/1/4), but succeeded in [the retry](https://drone.grafana.net/grafana/dskit/1421/1/1). Revision was https://github.com/grafana/dskit/pull/214/commits/f73a2dbcda33f09b8e800dcc411b4650da30ce0d

```
--- FAIL: TestRing_ShuffleShardWithLookback_CorrectnessWithFuzzy (88.81s)
    --- FAIL: TestRing_ShuffleShardWithLookback_CorrectnessWithFuzzy/num_instances_=_9,_num_zones_=_3,_update_oldest_registered_timestamp_=_true (0.02s)
        ring_test.go:1840: random generator seed: 1663955757664614088
        ring_test.go:1958: subring generated after event 4 is expected to include instance instance-6 from ring state at time 2022-09-23 19:11:57.669186493 +0000 UTC m=+4673.344713179 but it's missing (actual instances are: instance-9, instance-10, instance-2)
```

**Comment by julienduchesne** [comment]
Not flaky anymore. Haven't managed to trigger failures for those in hundreds of runs. See: https://github.com/grafana/dskit/pull/600. We can reopen if they show up again
