### ISSUE TITLE
Ring status page shows 100% ownership as "1e+02%"

### ISSUE THREAD

**Issue by charleskorn** [grafana/dskit#231]
If a ring has a single member, the HTML-formatted ring status page shows that member's ownership as `1e+02%`, rather than the more human-friendly `100%`:

<img width="1108" alt="Screenshot 2022-11-09 at 5 12 02 pm" src="https://user-images.githubusercontent.com/4017646/200753279-c1469c71-758c-4fe9-8de2-113508d5b372.png">

## Steps to reproduce 
(I'm using Mimir as an example, this issue doesn't appear to be Mimir-specific)

1. Start a Mimir cluster with the [`./development/mimir-monolithic-mode/compose-up.sh` script](https://github.com/grafana/mimir/blob/481839e1d598a410c3eff15f2a422e7f1405b604/development/mimir-monolithic-mode/compose-up.sh)
2. Visit http://localhost:8001/compactor/ring

Happy to submit a PR to fix this if you'd like.

**Comment by pstibrany** [comment]
> Happy to submit a PR to fix this if you'd like.

Yes, please do. Thank you.
