### ISSUE TITLE
Refactor Cache interfaces

### ISSUE THREAD

**Issue by lamida** [grafana/dskit#253]
I think we can simplify dskit in the following ways:

* Add a Delete method to Cache - If an LRU doesn't have a delete method it can be a no-op. If people feel strongly about not adding a Delete method that doesn't work, we can split the interface into `Cache` and `DeletableCache`.
*  Remove `cache.RemoteCacheClient` - it's an abstraction that's only used in a handful of places.
*  Remove `cache.MemcachedCache` - it's a wrapper around `remoteCache` which doesn't do much.
*  Remove `cache.RedisCache` - it's a wrapper around `remoteCache` which doesn't do much.
*  Rename and refactor methods in `cache.memcachedClient` to implement cache.Cache.
*  Rename and refactor methods in `cache.redisClient` to implement cache.Cache.

**Comment by pracucci** [comment]
@56quarters You were also mentioning about removing `cache.RemoteCacheClient` in another PR comment. You may want to share your thoughts here.
