### ISSUE TITLE
etcd mock client depends on etcd server packages

### ISSUE THREAD

**Issue by 56quarters** [grafana/dskit#40]
kv/etcd/mock.go depends on etcd server packages. The server package in turn pulls in `go.opentelemetry.io/otel` packages. This complicates using dskit in Tempo that pulls in conflicting versions of these otel packages.

Example from trying to use newer versions of dskit in Tempo:

```
$ go mod vendor
go: downloading github.com/google/flatbuffers v2.0.0+incompatible
go: downloading github.com/go-test/deep v1.0.7
go: finding module for package go.opentelemetry.io/otel/semconv
github.com/grafana/tempo/pkg/ring imports
        github.com/grafana/dskit/kv imports
        github.com/grafana/dskit/kv/etcd imports
        go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/otel/semconv: package go.opentelemetry.io/otel/semconv provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC2
```

A library attempting to be lightweight like dskit shouldn't be pulling in otel packages. We should refactor the mock etcd client (which we use for unit tests) in order to avoid pulling in the etcd server.

**Comment by aknuds1** [comment]
Thanks for reporting this, Nick!

**Comment by 56quarters** [comment]
As an experiment, I attempted to move the code that uses the etcd server to a `_test.go` file but it doesn't seem to fix the issue:

```
$ go mod tidy
go: finding module for package go.opentelemetry.io/otel/semconv
github.com/grafana/tempo/pkg/ring imports
        github.com/grafana/dskit/kv tested by
        github.com/grafana/dskit/kv.test imports
        go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/otel/semconv: package go.opentelemetry.io/otel/semconv provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC2
```

**Comment by 56quarters** [comment]
My plan for fixing this is to create an in-memory implementation of the etcd client that doesn't depend on the server. I hope to have a PR up for this later this week.
