### ISSUE TITLE
Bump to Go 1.20 in go.mod

### ISSUE THREAD

**Issue by cristaloleg** [grafana/dskit#419]
Hey, I see that `go.mod` version is set on Go 1.19, which is okay https://github.com/grafana/dskit/blob/main/go.mod#L3

However, as the author of one lib used in dskit (`cristalhq/hedgedhttp`), I would like to release `v0.10.0`, which requires Go 1.20 because of `errors.Join` functionality.

Any objections if I will make a PR bumping Go version in `dskit` ? The most popular Grafana's projects are already on Go 1.20-1.21. Thanks.

PS. It's somewhat funny that the library's author asks the upstream project to update something 😬

**Comment by pstibrany** [comment]
I think that would be fine. We want to support two latest Go versions, which is currently Go 1.21 and 1.20. When you send the PR, can you please update other mentions of 1.19 (`.drone/drone.jsonnet` and `yaml`, `vet.sh`) too?? Thank you!
