### ISSUE TITLE
Ring lifecycler stuck when increasing tokens and instance is already in the ring

### ISSUE THREAD

**Issue by pracucci** [grafana/dskit#73]
I've found a bug in the `ring.Lifecycler` which happens in the following scenario:
- Ingester is already registered in the ring with 64 tokens and `LEAVING` state
- Ingester is configured to store/load tokens from disk
- Ingester starts up with a tokens config change (from 64 to 128)

What we get is that ingester will never increase tokens to 128 and will never switch to ACTIVE in the ring.

_The issue should be easy to reproduce with a unit test._

**Comment by aknuds1** [comment]
I can try my hand at this issue.

**Comment by aknuds1** [comment]
Note to self: Tyler tipped that `benchmarkBatch` in ring_test.go is a good reference, and perhaps also `TestAddIngesterReplacesExistingTokens`.

**Comment by owen-d** [comment]
I just independently found this one @pracucci :sob: :laughing: .

**Comment by slim-bean** [comment]
#incident-2022-06-23-loki-prod-005-ingesters-hanging-on-restart

😐
